### ISSUE TITLE
 Multitouch?

### ISSUE THREAD

**Issue by Origami-Lemon** [LumpBloom7/osu-maimai#335]
Hello! How (or if) Can I enable Multitouch?

**Comment by LumpBloom7** [comment]
Duplicate of #257

Support for multitouch on Windows needs to be implemented by osu-framework, and is being tracked at https://github.com/ppy/osu-framework/issues/5033 and https://github.com/ppy/osu-framework/issues/1514. 

Mobile platforms already support multitouch out of the box.
