### ISSUE TITLE
Twin slides may overlap

### ISSUE THREAD

**Issue by Feodor0090** [LumpBloom7/osu-maimai#374]
I don't think that this is actually beatable.
![2022 08 12-22:49:37](https://user-images.githubusercontent.com/53872073/185004736-979d5acb-6c66-4efd-9ce4-a6a4be69b093.png)
![2022 08 12-22:59:42](https://user-images.githubusercontent.com/53872073/185004772-e7052f73-dc20-41b6-bafb-0a0e1a1738c9.png)

A check for slides so they won't pass the same points on playfield is necessary.

There are cases when sliders intersects that moving stars pass near-the-same point on screen at the same time. This is beatable because you don't have to follow the stars precisely, but still confusing.
![2022 08 12-23:01:35](https://user-images.githubusercontent.com/53872073/185004814-87ef30ca-2e08-45dd-8863-713a5372cd3e.png)

Also, it's offtopic in this issue, but i want to ask you add more slides paths. Especially complicated ones, like on 2nd screenshot. It will make the ruleset much more interesting to play.

**Comment by LumpBloom7** [comment]
I don't think the fact slide bodies intersecting like in the first screenshot is a bug. In fact official maimai charts made use of that quite often on higher difficulties.

![image](https://user-images.githubusercontent.com/12001167/185024847-18dbda78-c71c-4dfa-995a-6bb80b77ce81.png)


Currently all slide paths supported in maimai has already been implemented, and they cover a lot of use cases already especially if twins slides are used. I feel that adding complex paths may increase visual noise during gameplay, but open to suggestions on that.

**Comment by LumpBloom7** [comment]
2nd point has been indirectly addressed via https://github.com/LumpBloom7/sentakki/pull/394
