### ISSUE TITLE
BREAK colouring

### ISSUE THREAD

**Issue by Feodor0090** [LumpBloom7/osu-maimai#375]
Single notes/slides have cyan color.
Twins have yellow color.
But all BREAKs, both single and twins are orange. This reduces the readability, especially for slides.

I don't think that adding one more colour would work. Maybe, change the appearance of "approach lines" somehow for twins to make them more visible?

**Comment by LumpBloom7** [comment]
The approach lines currently prioritize using break color if any set contains a break note, they should prioritize twin color instead, and maimai(Finale/DX) already does this.
