### ISSUE TITLE
Twin notes may cause note during hold without warning

### ISSUE THREAD

**Issue by Feodor0090** [LumpBloom7/osu-maimai#376]
This is playable (on multitouch) and is a nice pattern, but the player should be warned that he need to click the note without releasing the hold. Maybe by yellow coloring.
![изображение](https://user-images.githubusercontent.com/53872073/185008263-d9a7257a-1b6a-4e83-be1f-39a2204b02a0.png)

**Comment by LumpBloom7** [comment]
The twin colour is meant to signal objects that have the same start time, and not the fact that they exist at the same time. Making it the latter would likely make the majority of notes yellow during multitouch gameplay, regardless of whether they are twins.

Surely the player can infer that they shouldn't let go of the hold to hit the stray tap, by the fact that the Hold has a bit more Hold left.

Tentatively closing as `won't fix`. Feel free to start a discussion on the discord if you feel strongly about this to gather more opinions.
