### ISSUE TITLE
iOS and iPadOS file support?

### ISSUE THREAD

**Issue by RenjiAkairu** [LumpBloom7/osu-maimai#383]
![ภาพ](https://user-images.githubusercontent.com/50196447/185940013-f2de68f5-13dc-4b7b-8cb4-e4de54127f5f.png)
i found osu! document in itunes but ios don't know .dll file. pull file .dll and boom! crash

sentakki ruleset will support ios when?

**Comment by LumpBloom7** [comment]
You can't just install rulesets on ios and android the same way as on PC. Sentakki (or any other rulesets) need to be built alongside osu for them to be playable on those platforms.

(this is a limitation imposed by the platform and/or application marketplace guidelines)
