### ISSUE TITLE
Error while opening ruleset in mobile

### ISSUE THREAD

**Issue by roxandtol** [LumpBloom7/osu-maimai#399]
Hello, I've downloaded sentakki, and I've tried it on my pc (linux), and it worked flawlessly, but when I put it on my phone (Realme 8i), it gave me an error
![Screenshot_2022-09-25-22-25-57-78_25a1a32208bbcdc1d450b7aa854bb161](https://user-images.githubusercontent.com/41841903/192163763-0b41f088-9ed1-445f-8da2-3d88ef726ee9.jpg)

**Comment by LumpBloom7** [comment]
You can't load dlls on mobile versions of osu!lazer, you'd need to make/find a build with the ruleset included. 

See: https://github.com/LumpBloom7/sentakki/issues/11
