### ISSUE TITLE
Freezes when playing a beatmap

### ISSUE THREAD

**Issue by ghost** [LumpBloom7/osu-maimai#437]
Footage:
https://user-images.githubusercontent.com/79811506/218376403-c94c2243-3027-4c26-be72-1345d3b044dd.mp4

Runtime log:
[runtime.log](https://github.com/LumpBloom7/sentakki/files/10718955/runtime.log)

osu!lazer version:
2023.207.0

sentakki version:
2023.208.0

Beatmap:
https://osu.ppy.sh/beatmapsets/44132#osu/138834

**Comment by LumpBloom7** [comment]
Thanks for reporting this crash, I somehow managed to not fix this in the last release. Will look into it today.

**Comment by LumpBloom7** [comment]
@ciulinuwu A new release has been published that contains the fix to this crash.
https://github.com/LumpBloom7/sentakki/releases/tag/2023.213.0
