### ISSUE TITLE
Playing sentakki causes unhandled error in osu

### ISSUE THREAD

**Issue by zeankundev** [LumpBloom7/osu-maimai#458]
Hi. When I try to play sentakki on a map before playing, the message shows as following:

![image](https://github.com/LumpBloom7/sentakki/assets/58360911/a31738e6-9f16-4004-8e0f-b1d3bc1efbc4)

When I look on the log, I notice one of the line missing its dependency.
```
2023-05-17 23:04:06 [error]: System.MissingFieldException: Field not found: 'osu.Game.Rulesets.Objects.HitObject.SampleControlPoint'.
```
Is there anything wrong with sentakki or what? Lazer build is currently at 2023.513.0-lazer.

**Comment by LumpBloom7** [comment]
Have you updated sentakki?

**Comment by zeankundev** [comment]
Yes, I did to the latest release.

**Comment by LumpBloom7** [comment]
Sorry I can't reproduce this. 

If you're on windows, could you right click the sentakki dll file, click properties, and screenshot the details pane.

**Comment by zeankundev** [comment]
to reproduce, drag the sentakki dll to the rulesets folder on %appdata%/osu/rulesets. 

here is the details pane results:

![image](https://github.com/LumpBloom7/sentakki/assets/58360911/896ce522-e25b-44f1-b394-8a6156d41af5)

**Comment by LumpBloom7** [comment]
@zeankundev Are you by any chance okay with demonstrating via Discord screenshare? (You don't have to speak if you don't wanna)

**Comment by LumpBloom7** [comment]
Closed due to lack of information. Please drop another reply if you still have issues.
