### ISSUE TITLE
sentakki causes unhandled error when playing

### ISSUE THREAD

**Issue by fantasyzhjk** [LumpBloom7/osu-maimai#559]
heres the log
[1708609744.runtime.log](https://github.com/LumpBloom7/sentakki/files/14374674/1708609744.runtime.log)

**Comment by LumpBloom7** [comment]
I just noticed myself, pulling the release. I'll make a new release later

**Comment by LumpBloom7** [comment]
Fixed with the release of [2024.222.0](https://github.com/LumpBloom7/sentakki/releases/tag/2024.222.0), please give that a try.
